{
 "title": "HVAC samdong",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "\bsummary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CO2 concentration avg",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "avg(co2)" }
   ]
  },
  {
   "title": "Temperature avg",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "avg(temperature)" }
   ]
  },
  {
   "title": "Humidity avg",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "avg(humidity)" }
   ]
  },
  {
   "title": "PM 10.0 avg",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(particulate_matter{pm=\"10.0\"})"
    }
   ]
  },
  {
   "title": "PM 2.5 avg",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(particulate_matter{pm=\"2.5\"})"
    }
   ]
  },
  {
   "title": "PM 1.0 avg",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(particulate_matter{pm=\"1.0\"})"
    }
   ]
  },
  { "title": "temperature and humidity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 7 },
   "targets": [
    { "expr": "temperature", "legendFormat": "temperature" }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 7 },
   "targets": [
    { "expr": "humidity", "legendFormat": "humidity" }
   ]
  },
  { "title": "air", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "CO2 concentration",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "targets": [
    { "expr": "co2", "legendFormat": "co2" }
   ]
  },
  { "title": "particulate matter", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Particulate matter",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "conμgm3" } },
   "targets": [
    { "expr": "particulate_matter", "legendFormat": "PM {{pm}}" }
   ]
  },
  {
   "title": "Particulate matter in 0.1L of air",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "targets": [
    { "expr": "in_0_1L_of_air", "legendFormat": "{{size}} μm" }
   ]
  }
 ]
}